services:
  backend:
    build:
      context: ./backend
      target: builder
    image: conciencia-backend:dev
    command: pnpm start:dev
    env_file: ./backend/.env
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - conciencia_net
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    env_file: ./backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - conciencia_net
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - conciencia_net
    restart: unless-stopped

networks:
  conciencia_net:
    driver: bridge

volumes:
  postgres_data:
    driver: local
