version: "3.8"

services:
  backend:
    build:
      context: ./backend
      target: builder # en dev usaremos el stage "builder" -> "runner" para prod
    image: journal-manager-backend:dev
    volumes:
      - ./backend:/app # monta todo tu código en /app
      - /app/node_modules # preserva node_modules de la imagen
    working_dir: /app # tu código entra directo en /app
    command: pnpm start:dev # "start:dev" = "nest start --watch"
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000" # expone tu app NestJS
    depends_on:
      - postgres
      - redis
    restart: always

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: journal_user
      POSTGRES_PASSWORD: journal_pass
      POSTGRES_DB: journal_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: always

volumes:
  postgres_data:
