version: "3.9"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    depends_on:
      - redis
    restart: always

  ai-service:
    build:
      context: ./ai-service
    ports:
      - "8000:8000"
    env_file:
      - ./ai-service/.env
    volumes:
      - ./ai-service:/app
    restart: always

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: always
