/*
  Warnings:

  - The values [INVESTIGACION_CIENTIFICA_TECNOLOGICA,INNOVACION_DESARROLLO,EDUCACION_CIENTIFICA_TECNOLOGICA,CIENCIA_SOCIEDAD,POLITICAS_PUBLICAS_CTI,PRODUCCION_DESARROLLO_LOCAL,BITACORAS_ESTUDIANTES,MUJERES_DIVERSIDADES_CIENCIA,PERSPECTIVA_FORMOSENIA,RECENSIONES_RESEÑA,DESARROLLO_SOFTWARE] on the enum `ThemeCategory` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "public"."ThemeCategory_new" AS ENUM ('INVESTIGACION_CIENTIFICA_Y_TECNOLOGICA', 'INNOVACION_Y_DESARROLLO_ID', 'EDUCACION_CIENTIFICA_Y_TECNOLOGICA', 'CIENCIA_Y_SOCIEDAD', 'POLITICAS_PUBLICAS_EN_CIENCIA_Y_TECNOLOGIA', 'PRODUCCION_Y_DESARROLLO_LOCAL', 'JUVENTUD_INVESTIGADORA', 'MUJERES_Y_DIVERSIDADES_EN_LA_CIENCIA', 'PERSPECTIVA_FORMOSENA', 'RECENSIONES_Y_RESEÑA', 'DESARROLLO_DE_SOFTWARE', 'TELECOMUNICACIONES', 'MECATRONICA', 'QUIMICA_INDUSTRIAL');
ALTER TABLE "public"."Theme" ALTER COLUMN "category" TYPE "public"."ThemeCategory_new" USING ("category"::text::"public"."ThemeCategory_new");
ALTER TYPE "public"."ThemeCategory" RENAME TO "ThemeCategory_old";
ALTER TYPE "public"."ThemeCategory_new" RENAME TO "ThemeCategory";
DROP TYPE "public"."ThemeCategory_old";
COMMIT;
